export const GET_METHOD = 'GET_METHOD';
export const GET_METHOD_COUNTRY = 'GET_METHOD_COUNTRY';
export const GET_METHOD_USER_DATA = 'GET_METHOD_USER_DATA'
export const GET_METHOD_BUDGET = 'GET_METHOD_BUDGET'
export const GET_METHOD_ABOUT_TOUCH = 'GET_METHOD_ABOUT_TOUCH'